"""create models table

Revision ID: 8e5c9eaec751
Revises: 
Create Date: 2025-10-02 18:04:03.986588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5c9eaec751'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('license', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('params_b', sa.Float(), nullable=True),
    sa.Column('quantizations', sa.String(), nullable=True),
    sa.Column('size_mb', sa.Integer(), nullable=True),
    sa.Column('memory_min_gb', sa.Float(), nullable=True),
    sa.Column('speed_cpu_tok_s', sa.Float(), nullable=True),
    sa.Column('speed_gpu_tok_s', sa.Float(), nullable=True),
    sa.Column('bench_mmlu', sa.Float(), nullable=True),
    sa.Column('bench_gsm8k', sa.Float(), nullable=True),
    sa.Column('hardware_target', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
